In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('cardekho_imputated.csv')
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [3]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## data cleaning

In [4]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15411 entries, 0 to 15410
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   car_name           15411 non-null  object
 1   brand              15411 non-null  object
 2   model              15411 non-null  object
 3   vehicle_age        15411 non-null  int64
 4   km_driven          15411 non-null  int64
 5   seller_type        15411 non-null  object
 6   fuel_type          15411 non-null  object
 7   transmission_type  15411 non-null  object
 8   mileage            15411 non-null  float64
 9   engine             15411 non-null  int64
 10  max_power          15411 non-null  float64
 11  seats              15411 non-null  int64
 12  selling_price      15411 non-null  int64
dtypes: float64(2), int64(5), object(6)
memory usage: 1.5+ MB

In [6]:
df.describe()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15411.000000,1.541100e+04,15411.000000,15411.000000,15411.000000,15411.000000,1.541100e+04
mean,6.036338,5.561648e+04,19.701151,1486.057751,100.588254,5.325482,7.749711e+05
std,3.013291,5.161855e+04,4.171265,521.106696,42.972979,0.807628,8.941284e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,0.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.560000e+05
75%,8.000000,7.000000e+04,22.700000,1582.000000,117.300000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [7]:
df.drop(columns=['car_name','brand'],axis=1,inplace=True)

In [8]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [9]:
df.model.value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [10]:
df.model.unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [11]:
## Indepedent and Depdendent Features
x = df.drop('selling_price',axis=1)
y = df['selling_price']

In [12]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

## Feature Encoding and Scaling

In [13]:
len(df.model.unique())

120

In [14]:
df.model.value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x['model'] = le.fit_transform(x['model'])

In [16]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [17]:
len(df.seller_type.unique()), len(df.fuel_type.unique()), len(df.transmission_type.unique())

(3, 5, 2)

In [18]:
## Create columns Transformer with 3 types of transformers
num_features = x.select_dtypes(exclude='object').columns
onehot_columns = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ('OneHotEncoder',oh_transformer,onehot_columns),
        ('StandardScaler',numeric_transformer,num_features)
    ],remainder='passthrough'
)

In [19]:
x = preprocessor.fit_transform(x)

In [20]:
pd.DataFrame(x)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=42)

## Model Traning and Model Selection

In [33]:
!pip install xgboost

Requirement already satisfied: xgboost in /Users/vaibhavkale/ML Learnings/venv/lib/python3.10/site-packages (3.0.0)
Requirement already satisfied: numpy in /Users/vaibhavkale/ML Learnings/venv/lib/python3.10/site-packages (from xgboost) (2.2.1)
Requirement already satisfied: scipy in /Users/vaibhavkale/ML Learnings/venv/lib/python3.10/site-packages (from xgboost) (1.15.1)

In [38]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge, Lasso, LinearRegression
from sklearn.ensemble import AdaBoostRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor

In [39]:
## Create a function to evaluate model
def evalute_model(true, predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2_sc = r2_score(true,predicted)
    return mae, rmse, r2_sc

In [41]:
## beggining model training
models = {
    "Linear regression" : LinearRegression(),
    "Lasso" : Lasso(),
    "Ridge" : Ridge(),
    "K Neighbors" : KNeighborsRegressor(),
    "DecisionTree" : DecisionTreeRegressor(),
    "Random Forest Regressor" : RandomForestRegressor(),
    "Adaboost" : AdaBoostRegressor(),
    "Gradient Boost" : GradientBoostingRegressor(),
    "XGBoost Regressor" : XGBRegressor()
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train,y_train)
    
    print(list(models.keys())[i])
    
    ## make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    
    ## Training Datasset
    print("Traning DataSet")
    print("R2 Score",r2_score(y_train,y_train_pred))
    print("MSE",mean_squared_error(y_train,y_train_pred))
    print("MAE ", mean_absolute_error(y_train,y_train_pred))
    print("RMSE ",np.sqrt(mean_squared_error(y_train,y_train_pred)))
    
    print("-------------------------------------------------------")
    
    ## Test Dataset
    print("Test Dataset")
    print("R2 Score",r2_score(y_test,y_test_pred))
    print("MSE",mean_squared_error(y_test,y_test_pred))
    print("MAE ", mean_absolute_error(y_test,y_test_pred))
    print("RMSE ",np.sqrt(mean_squared_error(y_test,y_test_pred)))
    
    print("="*35)
    print("\n")

Linear regression
Traning DataSet
R2 Score 0.6217719576765959
MSE 306756099359.75964
MAE  268101.6070829933
RMSE  553855.6665411664
-------------------------------------------------------
Test Dataset
R2 Score 0.6645109298852006
MSE 252550062888.5655
MAE  279618.5794158424
RMSE  502543.59302309836
===================================


Lasso
Traning DataSet
R2 Score 0.6217719518776927
MSE 306756104062.8718
MAE  268099.36385452165
RMSE  553855.6707869585
-------------------------------------------------------
Test Dataset
R2 Score 0.6645122032673858
MSE 252549104309.64417
MAE  279614.9121235311
RMSE  502542.6392950594
===================================


Ridge
Traning DataSet
R2 Score 0.6217710757960577
MSE 306756814595.5531
MAE  268060.01834024815
RMSE  553856.31222868
-------------------------------------------------------
Test Dataset
R2 Score 0.6645245808031837
MSE 252539786726.0844
MAE  279558.10573329584
RMSE  502533.3687687659
===================================


K Neighbors
Traning DataSet
R2 Score 0.8678233873382719
MSE 107199830762.49188
MAE  92348.62102530824
RMSE  327413.8524291419
-------------------------------------------------------
Test Dataset
R2 Score 0.9135498426709197
MSE 65078104221.74019
MAE  113605.9438858255
RMSE  255104.10467442538
===================================


DecisionTree
Traning DataSet
R2 Score 0.9994666998284044
MSE 432524990.53644824
MAE  5164.819922128488
RMSE  20797.23516567643
-------------------------------------------------------
Test Dataset
R2 Score 0.8795948660373801
MSE 90638792327.75165
MAE  124317.72894366959
RMSE  301062.7714078106
===================================


Random Forest Regressor
Traning DataSet
R2 Score 0.9818961164081801
MSE 14682879354.411604
MAE  39519.48670040753
RMSE  121172.93160772997
-------------------------------------------------------
Test Dataset
R2 Score 0.9273585773924194
MSE 54683140173.78197
MAE  101941.0371761172
RMSE  233844.2647870201
===================================


Adaboost
Traning DataSet
R2 Score 0.7932246677456535
MSE 167701987342.13922
MAE  284073.4560979707
RMSE  409514.331058315
-------------------------------------------------------
Test Dataset
R2 Score 0.7342686915329788
MSE 200037690175.25012
MAE  303007.3815657852
RMSE  447255.73241183854
===================================


Gradient Boost
Traning DataSet
R2 Score 0.9486642022282229
MSE 41635117759.266556
MAE  111666.19181998471
RMSE  204046.85187296214
-------------------------------------------------------
Test Dataset
R2 Score 0.9144580940374901
MSE 64394389131.804474
MAE  125976.03536866936
RMSE  253760.49560915597
===================================


XGBoost Regressor
Traning DataSet
R2 Score 0.9906142950057983
MSE 7612121600.0
MAE  61798.6015625
RMSE  87247.47331585023
-------------------------------------------------------
Test Dataset
R2 Score 0.9214508533477783
MSE 59130380288.0
MAE  97276.71875
RMSE  243167.39149812007
===================================

In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

def evaluate_model(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)
    return mae, rmse, r2

In [44]:
# Initialize few parameters for Hyperparameter tuning
knn_params = {"n_neighbors": [2, 3, 10, 20, 40, 50]}
rf_params = {
    "max_depth": [5, 8, 15, None, 10],
    "max_features": [5, 7, "auto", 8],
    "n_estimators": [100, 200, 500, 1000]
}
ada_params = {
    "n_estimators" : [50,60,70,80,90],
    "loss" : ['linear','square','exponential']
}

grad_params = {
    "loss" : ['squared_error', 'huber', 'absolute_error'],
    "criterion" : ['friedman_mse' ,'squared_error', 'mse'],
    "min_samples_split" : [2,8,15,20],
    "n_estimators" : [100,200,500,1000],
    "max_depth" : [5,8,15,None,10],
    "learning_rate" : [0.1,0.01,0.001]
}

xgboost_params = {
    "learning_rate" : [0.1, 0.01],
    "max_depth" : [5, 8, 12, 20, 30],
    "n_estimators" : [100, 200, 300],
    "colsample_bytree" : [0.5, 0.8, 1, 0.3, 0.4]
}

# Models List for Hyperparameter tuning
randomcv_models = [
    # ('KNN', KNeighborsRegressor(), knn_params),
    # ("RF", RandomForestRegressor(), rf_params),
    # ("ADB", AdaBoostRegressor(),ada_params),
    # ("GDBR",GradientBoostingRegressor(),grad_params),
    ("XGB",XGBRegressor(),xgboost_params)
]


from sklearn.model_selection import RandomizedSearchCV

model_param = {}

for name, model, params in randomcv_models:
    random = RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        n_iter=100,
        cv=3,
        verbose=2,
        n_jobs=-1
    )
    random.fit(x_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name}")
    print(model_param[model_name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=5, n_estimators=100; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=5, n_estimators=100; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=5, n_estimators=100; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.4s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.3s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   1.7s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.7s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   1.9s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=100; total time=   1.3s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=100; total time=   1.3s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=100; total time=   1.3s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   5.6s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   4.3s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   4.4s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   5.7s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=8, n_estimators=300; total time=   0.7s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=8, n_estimators=300; total time=   0.8s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   5.3s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=8, n_estimators=300; total time=   0.7s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=8, n_estimators=300; total time=   0.6s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   9.4s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=8, n_estimators=300; total time=   0.7s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=20, n_estimators=300; total time=  10.1s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=20, n_estimators=300; total time=  10.0s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=8, n_estimators=300; total time=   0.7s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.4s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   3.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.3s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=20, n_estimators=200; total time=   3.4s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=12, n_estimators=100; total time=   0.9s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=20, n_estimators=200; total time=   3.6s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=12, n_estimators=100; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=12, n_estimators=300; total time=   2.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=12, n_estimators=300; total time=   2.0s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=20, n_estimators=200; total time=   3.7s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=12, n_estimators=100; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=12, n_estimators=300; total time=   2.5s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.4s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.3s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=30, n_estimators=100; total time=   1.0s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.2s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=30, n_estimators=100; total time=   1.2s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=30, n_estimators=100; total time=   1.1s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=20, n_estimators=100; total time=   1.4s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=20, n_estimators=100; total time=   1.4s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=20, n_estimators=100; total time=   1.4s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   0.9s[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   1.0s

[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=5, n_estimators=300; total time=   0.3s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   0.9s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=5, n_estimators=300; total time=   0.3s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=5, n_estimators=300; total time=   0.3s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=12, n_estimators=200; total time=   1.2s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=12, n_estimators=200; total time=   1.3s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=12, n_estimators=200; total time=   1.3s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimators=300; total time=   0.6s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimators=300; total time=   0.6s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimators=300; total time=   0.6s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=200; total time=   1.8s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   5.1s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   5.2s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=200; total time=   1.5s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   5.5s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=8, n_estimators=100; total time=   0.4s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=8, n_estimators=100; total time=   0.4s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=12, n_estimators=200; total time=   1.7s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=8, n_estimators=100; total time=   0.4s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=20, n_estimators=200; total time=   1.8s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=20, n_estimators=200; total time=   1.9s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=20, n_estimators=200; total time=   1.9s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=12, n_estimators=300; total time=   1.6s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=12, n_estimators=300; total time=   1.8s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   3.8s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=12, n_estimators=300; total time=   2.0s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   4.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   4.1s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=20, n_estimators=300; total time=  10.8s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=20, n_estimators=300; total time=  10.8s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=8, n_estimators=100; total time=   0.3s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=20, n_estimators=300; total time=  10.9s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=8, n_estimators=100; total time=   0.3s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=8, n_estimators=300; total time=   0.6s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=8, n_estimators=300; total time=   0.5s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.2s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=8, n_estimators=300; total time=   0.5s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.4s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=30, n_estimators=300; total time=   6.0s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.4s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=30, n_estimators=300; total time=   5.6s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=30, n_estimators=300; total time=   5.9s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=12, n_estimators=300; total time=   3.2s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=12, n_estimators=300; total time=   3.3s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=12, n_estimators=300; total time=   3.3s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.7s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.8s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=5, n_estimators=100; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=5, n_estimators=100; total time=   0.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=5, n_estimators=100; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.8s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=8, n_estimators=300; total time=   0.7s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=8, n_estimators=300; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=30, n_estimators=300; total time=   9.8s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=8, n_estimators=300; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=30, n_estimators=300; total time=  10.5s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=30, n_estimators=100; total time=   6.0s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=20, n_estimators=100; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=30, n_estimators=100; total time=   5.9s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=30, n_estimators=300; total time=  10.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=20, n_estimators=100; total time=   1.1s
[CV] END colsample_bytree=0.8, learning_rate=0.1, max_depth=30, n_estimators=100; total time=   5.6s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   3.1s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=20, n_estimators=100; total time=   1.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   3.1s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   3.0s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=5, n_estimators=200; total time=   0.3s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=12, n_estimators=100; total time=   0.6s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=12, n_estimators=100; total time=   0.6s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=5, n_estimators=200; total time=   0.3s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=12, n_estimators=100; total time=   0.8s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=8, n_estimators=300; total time=   0.9s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=8, n_estimators=300; total time=   0.9s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=8, n_estimators=300; total time=   0.9s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.5s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=30, n_estimators=200; total time=   3.6s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=30, n_estimators=200; total time=   3.6s
[CV] END colsample_bytree=0.4, learning_rate=0.01, max_depth=8, n_estimators=200; total time=   0.4s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=30, n_estimators=200; total time=   3.4s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=0.5, learning_rate=0.1, max_depth=5, n_estimators=200; total time=   0.3s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=5, n_estimators=200; total time=   0.3s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=20, n_estimators=200; total time=   3.2s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=20, n_estimators=200; total time=   3.1s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=20, n_estimators=200; total time=   3.1s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   2.2s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   2.4s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   2.5s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.3s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.3s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=5, n_estimators=300; total time=   0.4s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=5, n_estimators=300; total time=   0.5s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=5, n_estimators=300; total time=   0.4s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.8, learning_rate=0.01, max_depth=5, n_estimators=300; total time=   0.4s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=8, n_estimators=100; total time=   0.2s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=20, n_estimators=300; total time=   4.3s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=20, n_estimators=300; total time=   4.4s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=20, n_estimators=300; total time=   5.7s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=20, n_estimators=300; total time=   5.8s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=5, n_estimators=100; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=20, n_estimators=300; total time=   5.8s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=5, n_estimators=100; total time=   0.1s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=5, n_estimators=100; total time=   0.1s
[CV] END colsample_bytree=1, learning_rate=0.1, max_depth=5, n_estimators=200; total time=   0.2s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=12, n_estimators=100; total time=   1.1s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=20, n_estimators=300; total time=   4.4s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=12, n_estimators=100; total time=   1.3s
[CV] END colsample_bytree=1, learning_rate=0.01, max_depth=12, n_estimators=100; total time=   1.1s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   1.4s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   1.5s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   5.4s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   5.2s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=20, n_estimators=300; total time=   5.4s
[CV] END colsample_bytree=0.5, learning_rate=0.01, max_depth=12, n_estimators=200; total time=   1.4s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=12, n_estimators=200; total time=   1.1s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=12, n_estimators=200; total time=   1.2s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=30, n_estimators=200; total time=   2.2s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=8, n_estimators=200; total time=   0.4s
[CV] END colsample_bytree=0.4, learning_rate=0.1, max_depth=8, n_estimators=200; total time=   0.4s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=30, n_estimators=200; total time=   2.2s
[CV] END colsample_bytree=0.3, learning_rate=0.01, max_depth=30, n_estimators=200; total time=   2.3s
[CV] END colsample_bytree=0.3, learning_rate=0.1, max_depth=12, n_estimators=200; total time=   1.1s

In [46]:

# Retraining the models with best parameters
models = {
    ## "Random Forest Regressor": RandomForestRegressor(n_estimators=200, n_jobs=-1),
    # "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=16, n_jobs=-1),
    # "Adaboost Regressor" : AdaBoostRegressor(n_estimators=80,loss='linear'),
    # "GradientBoost Regressor" : GradientBoostingRegressor(n_estimators= 500, min_samples_split= 15, max_depth= 15, loss= 'huber', learning_rate= 0.1, criterion= 'squared_error'),
    "XGBoost Regressor" : XGBRegressor(n_estimators=300,learning_rate=0.1,max_depth=5,colsample_bytree=0.5)
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train)  # Train model

    # Make predictions
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)
    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))
    print('----------------------------------')

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('='*35)
    print('\n')

XGBoost Regressor
Model performance for Training set
- Root Mean Squared Error: 113088.9462
- Mean Absolute Error: 74619.2188
- R2 Score: 0.9842
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 374231.2427
- Mean Absolute Error: 106923.5547
- R2 Score: 0.8140
===================================